apiVersion: v1
kind: Pod
metadata:
  name: postinstall-hook
  annotations:
    "helm.sh/hook": post-install
spec:
  containers:
    - name: postinstall-hook
      image: busybox
      command: ["sleep", "20"]
  restartPolicy: Never
