apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook
  annotations:
    "helm.sh/hook": pre-install
spec:
  containers:
    - name: preinstall-hook
      image: busybox
      command: ["sleep", "20"]
  restartPolicy: Never
