- name: Wipe app
  include_tasks: 0-wipe.yml
  tags:
    - web_app_full_wipe
  when: web_app_full_wipe == true

- name: Pull and start docker image
  block:
    - name: Pull docker image
      command: docker pull {{ web_app_repo_name }}:{{ web_app_version }}

    - name: Run container
      command: docker run -d -p {{ web_app_external_port }}:{{ web_app_internal_port }} {{ web_app_repo_name }}:{{ web_app_version }}
  tags:
    - web_app
  when: web_app_full_wipe == false