apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort  # Изменено с LoadBalancer на NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32128  # Вы можете указать конкретный порт или оставить Kubernetes выбрать автоматически
