apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-app
  template:
    metadata:
      labels:
        app: time-app
    spec:
      containers:
      - name: time-app
        image: n0m1nd/moscow_time_python
        env:
          - name: SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: credentials
                key: secret_token
        ports:
        - containerPort: 8081
