replicas: 1
image:
  repository: ernestmatskevich/moscow-time
  tag: latest
storage:
  size: 1Gi
service:
  port: 5000
serviceAccount:
  create: true
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: "example.local"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
