Vagrant.configure("2") do |config|

    config.vm.define "host1" do |host1|
      host1.vm.box = "hashicorp/bionic64"
    end
  
    config.vm.define "host2" do |host2|
      host2.vm.box = "hashicorp/bionic64"
    end
  
  end