locals {
  ENV_PG_USER     = "POSTGRES_USER=${var.PG_USER}"
  ENV_PG_PASSWORD = "POSTGRES_PASSWORD=${var.PG_PASSWORD}"
  ENV_PG_DBNAME   = "POSTGRES_DB=${var.PG_DBNAME}"
  ENV_ENV         = "ENV=${var.ENV}"
  ENV_SERVER_HOST = "SERVER_HOST=${var.SERVER_HOST}"
  ENV_DB_HOST     = "DB_HOST=${var.DB_HOST}"
  ENV_SERVER_PORT = "SERVER_PORT=${var.SERVER_PORT}"
}
