name: app_python

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
      - "app_python/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "app_python/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      
      - name: Download dependencies
        run: |
          pip install -r ./app_python/requirements.txt
      
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-foramat=github .
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      
      - name: Download dependencies
        run: |
          pip install -r ./app_python/requirements.txt
      
      - name: Test
        run: pytest ./app_python
    
  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_python/
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops:app_python
      
