name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./app_python/
        file: ./app_python/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_IMG_NAME }}:${{ github.event.release.tag_name }}
          ${{ secrets.DOCKER_IMG_NAME }}:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_IMG_NAME }}:cache
        cache-to: type=inline,mode=max