name: Docker CI

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      # Cache Docker layers with cache-to
      - name: Build Docker image with cache-to
        working-directory: ./app_python
        run: docker buildx build --cache-to type=local,dest=/tmp/.buildx-cache -t ${{ secrets.DOCKER_USERNAME }}/app_python .

      # Push Docker image
      - name: Push Docker image
        working-directory: ./app_python
        run: docker buildx build --cache-from type=local,src=/tmp/.buildx-cache -t ${{ secrets.DOCKER_USERNAME }}/app_python --push .
